manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: tmbutcher
      url-base: https://github.com/tmbutcher
  projects:
    - name: zmk
      remote: tmbutcher
      revision: dev
      import: app/west.yml
  self:
    path: config
