on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  ferris_sweep_elite_c:
    runs-on: ubuntu-latest
    name: Elite-C for Ferris Sweep

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache qmk toolchain
        uses: actions/cache@v2
        env:
          cache-name: qmk-toolchain
        with:
          path: |
            /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies for qmk build
        uses: mstksg/get-package@v1
        with:
          apt-get: git python3-pip dfu-util dfu-programmer avrdude 
      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .
      - name: Prepare qmk_firmware folder
        working-directory: ./qmk_firmware
        run: |
          mkdir -p keyboards/ferris/sweep/keymaps
          ln -s $(pwd)/../elite_c/ferris_sweep keyboards/ferris/sweep/keymaps/karl
      - name: Build ferris firmware
        working-directory: ./qmk_firmware
        run: qmk compile -km karl -kb ferris/sweep
      - name: Archive (Ferris Sweep)
        uses: actions/upload-artifact@v2
        with:
          name: elite_c_ferris_sweep
          path: qmk_firmware/ferris_sweep_karl.hex 


  kyria_nice_nano:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Kyria nice!nano
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare build env for west
        run: mv nice_nano_v2/kyria config
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Kyria Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=kyria_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Kyria DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano_v2.dts.pre.tmp
      - name: Kyria Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 kyria_left_nice_nano_v2.uf2
      - name: Archive (Kyria Left)
        uses: actions/upload-artifact@v2
        with:
          name: kyria_nice_nano_v2
          path: kyria_left_nice_nano_v2.uf2
      - name: West Build (Kyria Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=kyria_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Kyria Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 kyria_right_nice_nano_v2.uf2
      - name: Archive (Kyria Right)
        uses: actions/upload-artifact@v2
        with:
          name: kyria_nice_nano_v2
          path: kyria_right_nice_nano_v2.uf2

  sweep_nice_nano:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Ferris sweep nice!nano
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare build env for west
        run: mv nice_nano_v2/sweep config
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Kyria Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=kyria_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Kyria DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano_v2.dts.pre.tmp
      - name: Kyria Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 kyria_left_nice_nano_v2.uf2
      - name: Archive (Kyria Left)
        uses: actions/upload-artifact@v2
        with:
          name: sweep_nice_nano_v2
          path: kyria_left_nice_nano_v2.uf2
      - name: West Build (Kyria Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=kyria_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Kyria Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 kyria_right_nice_nano_v2.uf2
      - name: Archive (Kyria Right)
        uses: actions/upload-artifact@v2
        with:
          name: sweep_nice_nano_v2
          path: kyria_right_nice_nano_v2.uf2
